name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Authenticacao no docker hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{secrets.DOCKERHUB_USR}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Build and push Docker image worker
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./home-broker/01-worker
          file: ./home-broker/01-worker/Dockerfile
          push: true
          tags: |
            danielllmuniz/trader-worker:${{github.run_number}}
            danielllmuniz/trader-worker:latest
      - name: Build and push Docker image api
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./home-broker/02-api
          file: ./home-broker/02-api/Dockerfile
          push: true
          tags: |
            danielllmuniz/trader-api:${{github.run_number}}
            danielllmuniz/trader-api:latest
      - name: Build and push Docker image web
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./home-broker/03-frontend
          file: ./home-broker/03-frontend/Dockerfile
          push: true
          tags: |
            danielllmuniz/trader-web:${{github.run_number}}
            danielllmuniz/trader-web:latest
          build-args: |
            NEXT_PUBLI_NEST_URL: http://test.com
            NEXT_PUBLI_NEST_URL_API: http://api.test.com
          
          
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Configurar credenciais de acesso
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-key-id: ${{secrets.AWS_SECRET_KEY}}
          aws-region: us-east-1
      - name: Configuracao do Kubeconfig
        shell: bash
        run: |
          aws eks update-kubeconfig --name imersao-eks --region us-east-1
      - name: Deploy to Kubernetes cluster worker
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            home-broker/04-k8s-deploy/02-worker/deployment.yaml
          images: |
            danielllmuniz/trader-worker:${{github.run_number}}
      - name: Deploy to Kubernetes cluster api
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            home-broker/04-k8s-deploy/03-api/deployment.yaml
          images: |
            danielllmuniz/trader-api:${{github.run_number}}
      - name: Deploy to Kubernetes cluster frontend
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            home-broker/04-k8s-deploy/04-frontend/deployment.yaml
          images: |
            danielllmuniz/trader-web:${{github.run_number}}
            
          
