name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Authenticacao no docker hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{secrets.DOCKERHUB_USR}}
          password: ${{secrets.DOCKERHUB_PWD}}
      - name: Build and push Docker image worker
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./home-broker/01-worker
          file: ./home-broker/01-worker/Dockerfile
          push: true
          tags: |
            danielllmuniz/trader-worker:${{github.run_number}}
            danielllmuniz/trader-worker:latest
      - name: Build and push Docker image api
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./home-broker/02-api
          file: ./home-broker/02-api/Dockerfile
          push: true
          tags: |
            danielllmuniz/trader-api:${{github.run_number}}
            danielllmuniz/trader-api:latest
      - name: Build and push Docker image web
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./home-broker/03-web
          file: ./home-broker/03-web/Dockerfile
          push: true
          tags: |
            danielllmuniz/trader-web:${{github.run_number}}
            danielllmuniz/trader-web:latest
          build-args: |
            NEXT_PUBLI_NEST_URL: ${{secrets.NEXT_PUBLI_NEST_URL}}
            NEXT_PUBLI_NEST_URL_API: ${{secrets.NEXT_PUBLI_NEST_URL_API}}
          
          
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Passo 01
        run: echo "Baixar a base de codigo"
      - name: Passo 02
        run: echo "Authenticar na aws"
      - name: Passo 03
        run: echo "Deploy no microservico"
    
